function apply_paper_axes_style(ax)
%APPLY_PAPER_AXES_STYLE Apply a consistent paper-style appearance to axes.

set(ax, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 11, ...
    'LineWidth', 0.9, ...
    'Box', 'off', ...
    'Layer', 'top', ...
    'TickDir', 'out', ...
    'TickLength', [0.012 0.012], ...
    'XMinorGrid', 'on', ...
    'YMinorGrid', 'on', ...
    'GridLineStyle', '--', ...
    'MinorGridLineStyle', ':', ...
    'GridAlpha', 0.15, ...
    'MinorGridAlpha', 0.08);

grid(ax, 'on');

% Avoid manual position edits for tiledlayout-managed axes.
if isempty(ax.Layout) || ~isa(ax.Layout, 'matlab.graphics.layout.TiledChartLayoutOptions')
    outer_pos = get(ax, 'OuterPosition');
    tight_inset = get(ax, 'TightInset');
    left = outer_pos(1) + tight_inset(1);
    bottom = outer_pos(2) + tight_inset(2);
    ax_width = outer_pos(3) - tight_inset(1) - tight_inset(3);
    ax_height = outer_pos(4) - tight_inset(2) - tight_inset(4) - 0.04;
    set(ax, 'Position', [left, bottom, ax_width, ax_height]);
end

ttl = ax.Title;
set(ttl, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 12, ...
    'FontWeight', 'normal');
end
