function T = build_step9_weight_calibration_table(results)
%BUILD_STEP9_WEIGHT_CALIBRATION_TABLE Build a summary table for weight calibration.

rows = [];

for i = 1:numel(results)
    cfg = results(i).config;
    row = table( ...
        cfg.utility_weight_timely, ...
        cfg.utility_weight_reliability, ...
        cfg.utility_weight_cost, ...
        cfg.utility_weight_position_risk, ...
        cfg.utility_weight_event, ...
        results(i).objective, ...
        results(i).overall_emergency_timely, ...
        results(i).posdeg_emergency_timely, ...
        results(i).overall_timely, ...
        results(i).avg_tx_cost, ...
        results(i).posdeg_avg_tx_cost, ...
        results(i).loss_rate, ...
        'VariableNames', {'WTimely', 'WReliability', 'WCost', 'WPosRisk', 'WEvent', ...
        'Objective', 'EmergencyTimelyMean', 'PosDegEmergencyTimelyMean', ...
        'TimelyMean', 'AvgTxCostMean', 'PosDegAvgTxCostMean', 'LossRateMean'});

    if isempty(rows)
        rows = row;
    else
        rows = [rows; row]; %#ok<AGROW>
    end
end

T = sortrows(rows, 'Objective', 'descend');
end
