function T_summary = build_step12_stage_summary_table(T_raw_stage)
%BUILD_STEP12_STAGE_SUMMARY_TABLE Aggregate Step 12 stage metrics across seeds.

methods = unique(T_raw_stage.Method, 'stable');
stages = unique(T_raw_stage.Stage, 'stable');
rows = [];

for i = 1:numel(methods)
    for j = 1:numel(stages)
        subT = T_raw_stage(T_raw_stage.Method == methods(i) & T_raw_stage.Stage == stages(j), :);
        row = table( ...
            methods(i), ...
            stages(j), ...
            mean(subT.AvgDelay_s, 'omitnan'), std(subT.AvgDelay_s, 0, 'omitnan'), ci95(subT.AvgDelay_s), ...
            mean(subT.TimelyRate, 'omitnan'), std(subT.TimelyRate, 0, 'omitnan'), ci95(subT.TimelyRate), ...
            mean(subT.LossRate, 'omitnan'), std(subT.LossRate, 0, 'omitnan'), ci95(subT.LossRate), ...
            mean(subT.AvgTxCost, 'omitnan'), std(subT.AvgTxCost, 0, 'omitnan'), ci95(subT.AvgTxCost), ...
            mean(subT.EmergencyTimelyRate, 'omitnan'), std(subT.EmergencyTimelyRate, 0, 'omitnan'), ci95(subT.EmergencyTimelyRate), ...
            'VariableNames', { ...
            'Method', 'Stage', ...
            'AvgDelayMean_s', 'AvgDelayStd_s', 'AvgDelayCI95_s', ...
            'TimelyRateMean', 'TimelyRateStd', 'TimelyRateCI95', ...
            'LossRateMean', 'LossRateStd', 'LossRateCI95', ...
            'AvgTxCostMean', 'AvgTxCostStd', 'AvgTxCostCI95', ...
            'EmergencyTimelyRateMean', 'EmergencyTimelyRateStd', 'EmergencyTimelyRateCI95'});

        if isempty(rows)
            rows = row;
        else
            rows = [rows; row]; %#ok<AGROW>
        end
    end
end

T_summary = rows;
end

function value = ci95(x)
x = x(~isnan(x));
if isempty(x)
    value = NaN;
else
    value = 1.96 * std(x, 0) / sqrt(numel(x));
end
end
