function T = build_step11_sensitivity_table(results)
%BUILD_STEP11_SENSITIVITY_TABLE Convert Step 11 results into a table.

rows = [];

for i = 1:numel(results)
    row = table( ...
        results(i).param_name, ...
        results(i).param_value, ...
        results(i).default_value, ...
        results(i).avg_delay_s, ...
        results(i).timely_rate, ...
        results(i).loss_rate, ...
        results(i).avg_tx_cost, ...
        results(i).emergency_timely_rate, ...
        results(i).posdeg_avg_delay_s, ...
        results(i).posdeg_timely_rate, ...
        results(i).posdeg_loss_rate, ...
        results(i).posdeg_avg_tx_cost, ...
        results(i).posdeg_emergency_timely_rate, ...
        'VariableNames', { ...
        'Parameter', 'Value', 'DefaultValue', 'AvgDelay_s', 'TimelyRate', ...
        'LossRate', 'AvgTxCost', 'EmergencyTimelyRate', 'PosDegAvgDelay_s', ...
        'PosDegTimelyRate', 'PosDegLossRate', 'PosDegAvgTxCost', ...
        'PosDegEmergencyTimelyRate'});

    if isempty(rows)
        rows = row;
    else
        rows = [rows; row]; %#ok<AGROW>
    end
end

T = sortrows(rows, {'Parameter', 'Value'});
end
