function T_summary = build_step12_summary_table(T_raw)
%BUILD_STEP12_SUMMARY_TABLE Aggregate Step 12 overall metrics across seeds.

methods = unique(T_raw.Method, 'stable');
rows = [];

for i = 1:numel(methods)
    subT = T_raw(T_raw.Method == methods(i), :);
    row = table( ...
        methods(i), ...
        mean(subT.AvgDelay_s, 'omitnan'), std(subT.AvgDelay_s, 0, 'omitnan'), ci95(subT.AvgDelay_s), ...
        mean(subT.TimelyRate, 'omitnan'), std(subT.TimelyRate, 0, 'omitnan'), ci95(subT.TimelyRate), ...
        mean(subT.LossRate, 'omitnan'), std(subT.LossRate, 0, 'omitnan'), ci95(subT.LossRate), ...
        mean(subT.AvgTxCost, 'omitnan'), std(subT.AvgTxCost, 0, 'omitnan'), ci95(subT.AvgTxCost), ...
        mean(subT.EmergencyTimelyRate, 'omitnan'), std(subT.EmergencyTimelyRate, 0, 'omitnan'), ci95(subT.EmergencyTimelyRate), ...
        'VariableNames', { ...
        'Method', ...
        'AvgDelayMean_s', 'AvgDelayStd_s', 'AvgDelayCI95_s', ...
        'TimelyRateMean', 'TimelyRateStd', 'TimelyRateCI95', ...
        'LossRateMean', 'LossRateStd', 'LossRateCI95', ...
        'AvgTxCostMean', 'AvgTxCostStd', 'AvgTxCostCI95', ...
        'EmergencyTimelyRateMean', 'EmergencyTimelyRateStd', 'EmergencyTimelyRateCI95'});

    if isempty(rows)
        rows = row;
    else
        rows = [rows; row]; %#ok<AGROW>
    end
end

T_summary = rows;
end

function value = ci95(x)
x = x(~isnan(x));
if isempty(x)
    value = NaN;
else
    value = 1.96 * std(x, 0) / sqrt(numel(x));
end
end
