function T_summary = build_step13_summary_table(T_raw)
%BUILD_STEP13_SUMMARY_TABLE Aggregate Step 13 results by scenario and method.

scenario_ids = unique(T_raw.ScenarioID, 'stable');
methods = unique(T_raw.Method, 'stable');
rows = [];

for i = 1:numel(scenario_ids)
    scenario_rows = T_raw(T_raw.ScenarioID == scenario_ids(i), :);
    gnss_level = scenario_rows.GNSSLevel(1);
    rsu_level = scenario_rows.RSULevel(1);
    load_level = scenario_rows.LoadLevel(1);

    for j = 1:numel(methods)
        subT = scenario_rows(scenario_rows.Method == methods(j), :);
        row = table( ...
            scenario_ids(i), ...
            gnss_level, ...
            rsu_level, ...
            load_level, ...
            methods(j), ...
            mean(subT.AvgDelay_s, 'omitnan'), ...
            mean(subT.TimelyRate, 'omitnan'), ...
            mean(subT.LossRate, 'omitnan'), ...
            mean(subT.AvgTxCost, 'omitnan'), ...
            mean(subT.EmergencyTimelyRate, 'omitnan'), ...
            mean(subT.PosDegEmergencyTimelyRate, 'omitnan'), ...
            mean(subT.EffectiveWarningRate, 'omitnan'), ...
            mean(subT.EffectiveCoverage, 'omitnan'), ...
            mean(subT.EffectiveCount, 'omitnan'), ...
            'VariableNames', {'ScenarioID', 'GNSSLevel', 'RSULevel', 'LoadLevel', 'Method', ...
            'AvgDelayMean_s', 'TimelyRateMean', 'LossRateMean', 'AvgTxCostMean', ...
            'EmergencyTimelyRateMean', 'PosDegEmergencyTimelyRateMean', ...
            'EffectiveWarningRateMean', 'EffectiveCoverageMean', 'EffectiveCountMean'});

        if isempty(rows)
            rows = row;
        else
            rows = [rows; row]; %#ok<AGROW>
        end
    end
end

T_summary = rows;
end
