function params = get_moderate_forest_geometry_mainline_params()
%GET_MODERATE_FOREST_GEOMETRY_MAINLINE_PARAMS
% Data-informed moderate forest degradation setting. This is a deployable
% middle case between Default and the original ForestGeometry stress test.

base_params = get_default_step9_mainline_params();
stress_params = get_forest_geometry_mainline_params();
alpha = 0.45;
params = base_params;

interp_names = { ...
    'link_distance_scale', ...
    'pathloss_los_offset_dB', ...
    'pathloss_los_exponent', ...
    'pathloss_nlos_offset_dB', ...
    'pathloss_nlos_exponent', ...
    'nlosv_extra_loss_dB', ...
    'interference_scale', ...
    'blind_link_loss_scale_dB', ...
    'blind_interference_scale_dB', ...
    'position_gnss_independent_noise_std', ...
    'position_gnss_multipath_noise_std', ...
    'position_blind_zone_sigma_penalty', ...
    'position_blind_zone_score_penalty', ...
    'position_rsu_relief_cap', ...
    'position_alpha_blind_scale', ...
    'position_alpha_max', ...
    'blind_zone_trigger_threshold', ...
    'rsu_event_trigger_threshold', ...
    'env_event_trigger_threshold', ...
    'confidence_regime_blind_threshold', ...
    'confidence_regime_qpos_threshold', ...
    'utility_blind_protection_threshold', ...
    'utility_blind_pos_threshold', ...
    'utility_blind_relay_threshold', ...
    'utility_low_risk_guard_threshold', ...
    'utility_low_risk_blind_threshold', ...
    'deadline_coop', ...
    'deadline_emergency', ...
    'deadline_coop_physical', ...
    'deadline_emergency_physical'};

for i = 1:numel(interp_names)
    name = interp_names{i};
    if isfield(base_params, name) && isfield(stress_params, name) ...
            && isnumeric(base_params.(name)) && isnumeric(stress_params.(name))
        params.(name) = (1.0 - alpha) * base_params.(name) + alpha * stress_params.(name);
    end
end

params.tx_power_dBm = (1.0 - alpha) * base_params.tx_power_dBm + alpha * stress_params.tx_power_dBm;
params.noise_floor_dBm = base_params.noise_floor_dBm;
params.use_veg_attenuation = true;
params.veg_attenuation_scale = 0.55;

params.forest_calibration.enabled = true;
params.forest_calibration.mode = "ModerateForestGeometry";
params.forest_calibration.description = ...
    "Moderate deployable forest degradation interpolated between Default and ForestGeometry stress-test settings.";
params.forest_calibration.alpha_to_stress = alpha;
if isfield(stress_params, 'forest_calibration') && isfield(stress_params.forest_calibration, 'stats')
    params.forest_calibration.stats = stress_params.forest_calibration.stats;
end
end
