function write_step61_applicability_boundary_report_cn(applicability, failure_boundary, ...
    dcc_overtake, small_gain, out_path)
%WRITE_STEP61_APPLICABILITY_BOUNDARY_REPORT_CN Write Step61 CN report.

fid = fopen(out_path, 'w', 'n', 'UTF-8');
if fid == -1
    error('Could not open Step61 report file: %s', out_path);
end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>

fprintf(fid, '# Step61 适用边界更新报告\n\n');
fprintf(fid, '本步骤汇总 Step58、Step59、Step60 证据链，目标是明确主方法的有效区间、平稳退化区间和失败边界。该步骤不重调 `Risk-constrained-v6`，不删除 `10019/10013 ForestGeometry` 负例。\n\n');

fprintf(fid, '## 1. 适用性分类统计\n\n');
write_count_table_local(fid, applicability.ApplicabilityClass, 'ApplicabilityClass');

fprintf(fid, '\n## 2. 适用性总表\n\n');
fprintf(fid, '| Source | Scene | Config | Class | Baseline ceiling | Emergency feasibility | Overlap | Cost-gain | Stronger baseline | Note |\n');
fprintf(fid, '|---|---|---|---|---|---|---|---|---|---|\n');
for i = 1:height(applicability)
    fprintf(fid, '| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |\n', ...
        sanitize_md_local(applicability.EvidenceSource(i)), ...
        sanitize_md_local(applicability.Scene(i)), ...
        sanitize_md_local(applicability.Config(i)), ...
        sanitize_md_local(applicability.ApplicabilityClass(i)), ...
        sanitize_md_local(applicability.BaselineTimelyCeiling(i)), ...
        sanitize_md_local(applicability.EmergencyFeasibility(i)), ...
        sanitize_md_local(applicability.NlosBlindGnssOverlap(i)), ...
        sanitize_md_local(applicability.CostGainTradeoff(i)), ...
        sanitize_md_local(applicability.StrongerBaselineDecision(i)), ...
        sanitize_md_local(applicability.ApplicabilityNote(i)));
end

fprintf(fid, '\n## 3. 失败/边界场景\n\n');
fprintf(fid, '| Source | Scene | Config | Boundary class | Delta timely vs heuristic (pp) | Delta emergency vs heuristic (pp) | Cost delta (%%) | Stronger baseline | Reason |\n');
fprintf(fid, '|---|---|---|---|---:|---:|---:|---|---|\n');
for i = 1:height(failure_boundary)
    fprintf(fid, '| %s | %s | %s | %s | %.3f | %.3f | %.3f | %s | %s |\n', ...
        sanitize_md_local(failure_boundary.EvidenceSource(i)), ...
        sanitize_md_local(failure_boundary.Scene(i)), ...
        sanitize_md_local(failure_boundary.Config(i)), ...
        sanitize_md_local(failure_boundary.BoundaryClass(i)), ...
        failure_boundary.TimelyDeltaVsHeuristic_pp(i), ...
        failure_boundary.EmergencyDeltaVsHeuristic_pp(i), failure_boundary.CostDeltaVsHeuristic_pct(i), ...
        sanitize_md_local(failure_boundary.StrongerBaselineDecision(i)), ...
        sanitize_md_local(failure_boundary.PrimaryReason(i)));
end

fprintf(fid, '\n## 4. DCC/AoI strengthened baseline overtake analysis\n\n');
fprintf(fid, '`DCC-CBR-window` 与 `AoI-greedy` 是 literature-inspired baselines，不是完整 ETSI DCC 协议栈或 AoI 最优调度策略。该表用于说明主方法面对更强简化基线时的胜负边界。\n\n');
fprintf(fid, '| Source | Scene | Config | Delta vs DCC-CBR (pp) | Delta vs AoI-greedy (pp) | Overtake class |\n');
fprintf(fid, '|---|---|---|---:|---:|---|\n');
for i = 1:height(dcc_overtake)
    fprintf(fid, '| %s | %s | %s | %.3f | %.3f | %s |\n', ...
        sanitize_md_local(dcc_overtake.EvidenceSource(i)), ...
        sanitize_md_local(dcc_overtake.Scene(i)), ...
        sanitize_md_local(dcc_overtake.Config(i)), ...
        dcc_overtake.TimelyGainVsDCCWindow_pp(i), dcc_overtake.TimelyGainVsAoIGreedy_pp(i), ...
        sanitize_md_local(dcc_overtake.OvertakeClass(i)));
end

fprintf(fid, '\n## 5. 小增益场景解释口径\n\n');
fprintf(fid, '| Source | Scene | Config | Baseline | Gain (pp) | Stronger decision | Interpretation |\n');
fprintf(fid, '|---|---|---|---|---:|---|---|\n');
for i = 1:height(small_gain)
    fprintf(fid, '| %s | %s | %s | %s | %.3f | %s | %s |\n', ...
        sanitize_md_local(small_gain.EvidenceSource(i)), ...
        sanitize_md_local(small_gain.Scene(i)), ...
        sanitize_md_local(small_gain.Config(i)), ...
        sanitize_md_local(small_gain.ReferenceBaseline(i)), ...
        small_gain.ReferenceGain_pp(i), ...
        sanitize_md_local(small_gain.StrongerBaselineDecision(i)), ...
        sanitize_md_local(small_gain.SmallGainInterpretation(i)));
end

fprintf(fid, '\n## 6. 论文写作约束\n\n');
fprintf(fid, '1. `EffectiveRegime` 可作为主结果讨论，但不得推广为所有林区场景支配。\n');
fprintf(fid, '2. `GracefulDegradation` 应写为高基线天花板、低风险开放道路或弱 cost-gain 区间中的平稳退化。\n');
fprintf(fid, '3. `FailureBoundary` 必须保留，尤其是原 `10019/10013 ForestGeometry` 负例和 Step60 中的物理 emergency headroom 边界。\n');
fprintf(fid, '4. `ModerateForestGeometry` 是补充可部署场景；原 `ForestGeometry` 仍是 extreme stress / boundary case。\n');
end

function write_count_table_local(fid, values, name)
[groups, labels] = findgroups(values);
counts = splitapply(@numel, values, groups);
fprintf(fid, '| %s | Count |\n', name);
fprintf(fid, '|---|---:|\n');
for i = 1:numel(labels)
    fprintf(fid, '| %s | %d |\n', labels(i), counts(i));
end
end

function value = sanitize_md_local(value)
value = string(value);
value = replace(value, newline, ' ');
value = replace(value, '|', '/');
value = char(value);
end
